# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name (set in params.yaml under hugoblox.branding.name)
title: 'Infinitos Contrastes'
# Website URL
baseURL: 'https://imalexissaez.github.io/'

############################
## LANGUAGE
############################

defaultContentLanguage: es
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## PAGE OPTIONS
############################

cascade:
  - _target:
      path: /slides/**
      kind: page
      outputs: [HTML, present]

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: Lanczos
  quality: 90
  anchor: Smart
  hint: picture
timeout: "600s"
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
